development:
  clients:
    default:
      database: smartwall_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: smartwall_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>